version: "3.3"
services:
  backend:
    # 无需配置端口映射, 只需要expose服务端口并告知traefik该端口即可
    image: registry.cn-hangzhou.aliyuncs.com/baizhukui-image-repo/mall-admin-be:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # 指定访问该服务使用的域名
      - "traefik.http.routers.cicd-test-springboot.rule=Host(`mall-admin.be.baizhukui.com`)"
      - "traefik.http.routers.cicd-test-springboot.tls=true"
      # 告知traefik需要做反向代理的容器内端口
      - "traefik.http.services.cicd-test-springboot.loadbalancer.server.port=8080"
    networks:
      - traefik
networks:
  traefik:
    external: true