// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addapt": {
            "post": {
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]添加部门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "所属商场ID",
                        "name": "father_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "部门编码 varchar(15)",
                        "name": "apt_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "部门名称 varchar(63)",
                        "name": "apt_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "部门地址 varchar(255)",
                        "name": "apt_address",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "部门电话 varchar(255)",
                        "name": "apt_tel",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/addmall": {
            "post": {
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]添加商场",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商场编码 varchar(15)",
                        "name": "mall_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商场名称 varchar(63)",
                        "name": "mall_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商场地址 varchar(255)",
                        "name": "mall_address",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商场电话 varchar(255)",
                        "name": "mall_tel",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/addstaff": {
            "post": {
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]添加员工",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "所属部门ID",
                        "name": "father_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "员工编码 varchar(15)",
                        "name": "staff_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "员工姓名 varchar(63)",
                        "name": "staff_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "员工岗位 varchar(255)",
                        "name": "staff_pos",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "员工电话 varchar(255)",
                        "name": "staff_tel",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "员工薪水",
                        "name": "staff_sal",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/adduser": {
            "post": {
                "description": "add user",
                "tags": [
                    "root_api"
                ],
                "summary": "[3]增加用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账号 varchar(31)",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码 varchar(127)",
                        "name": "passwd",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "账号权限等级",
                        "name": "grade",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "若失败，\"code\": -1,\"msg\": 失败原因",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/deleteapt": {
            "post": {
                "description": "需确认操作：此操作会将所有所属员工删除",
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]删除部门（连锁删除）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "部门ID",
                        "name": "ID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/deletemall": {
            "post": {
                "description": "需确认操作：此操作会将所有所属部门和员工删除",
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]删除商场（连锁删除）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "商场ID",
                        "name": "ID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/deletestaff": {
            "post": {
                "description": "需确认操作",
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]删除员工",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "员工ID",
                        "name": "ID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/editapt": {
            "post": {
                "description": "进入修改界面后，将原来的值填入对应输入框",
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]修改部门信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "部门ID",
                        "name": "ID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "部门编码 varchar(15)",
                        "name": "apt_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "部门名称 varchar(63)",
                        "name": "apt_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "部门地址 varchar(255)",
                        "name": "apt_address",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "部门电话 varchar(255)",
                        "name": "apt_tel",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/editmall": {
            "post": {
                "description": "进入修改界面后，将原来的值填入对应输入框",
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]修改商场信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "商场ID",
                        "name": "ID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商场编码 varchar(15)",
                        "name": "mall_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商场名称 varchar(63)",
                        "name": "mall_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商场地址 varchar(255)",
                        "name": "mall_address",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "商场电话 varchar(255)",
                        "name": "mall_tel",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/editstaff": {
            "post": {
                "description": "进入修改界面后，将原来的值填入对应输入框",
                "tags": [
                    "admin_api"
                ],
                "summary": "[2]修改员工信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "员工ID",
                        "name": "ID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "员工编码 varchar(15)",
                        "name": "staff_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "员工姓名 varchar(63)",
                        "name": "staff_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "员工岗位 varchar(255)",
                        "name": "staff_pos",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "员工电话 varchar(255)",
                        "name": "staff_tel",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "员工薪水",
                        "name": "staff_sal",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_success"
                        }
                    }
                }
            }
        },
        "/getaptlist": {
            "post": {
                "description": "father_id为空则获取所有",
                "tags": [
                    "member_api"
                ],
                "summary": "[1]获取部门信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "father_id",
                        "name": "father_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "页号(默认1)",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "页大小(默认20)",
                        "name": "size",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键字(针对编码和名称的%*%)",
                        "name": "keyword",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/define.Res_get_success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/define.Res_get_success_data"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.ApartmentBasic"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/getmalllist": {
            "post": {
                "tags": [
                    "member_api"
                ],
                "summary": "[1]获取所有商场信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页号(默认1)",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "页大小(默认20)",
                        "name": "size",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键字(针对编码和名称的%*%)",
                        "name": "keyword",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/define.Res_get_success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/define.Res_get_success_data"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.MallBasic"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/getstafflist": {
            "post": {
                "description": "father_id为空则获取所有",
                "tags": [
                    "member_api"
                ],
                "summary": "[1]获取员工信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "father_id",
                        "name": "father_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "页号(默认1)",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "页大小(默认20)",
                        "name": "size",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键字(针对编码和名称的%*%)",
                        "name": "keyword",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/define.Res_get_success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/define.Res_get_success_data"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.StaffBasic"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "public_api"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账号 varchar(31)",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码 varchar(127)",
                        "name": "passwd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "grade可用于展示，也可用于隐藏无权限功能\u003cbr\u003e\u003cbr\u003e失败则返回 {\"code\": -1,\"msg\": \"$reason\"}",
                        "schema": {
                            "$ref": "#/definitions/define.Res_login_success"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "do ping",
                "tags": [
                    "public_api"
                ],
                "summary": "ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "define.Res_get_success": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 1
                },
                "data": {
                    "$ref": "#/definitions/define.Res_get_success_data"
                }
            }
        },
        "define.Res_get_success_data": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 1
                },
                "list": {}
            }
        },
        "define.Res_login_success": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 1
                },
                "data": {
                    "$ref": "#/definitions/define.Res_login_success_data"
                }
            }
        },
        "define.Res_login_success_data": {
            "type": "object",
            "properties": {
                "grade": {
                    "type": "integer",
                    "example": 2
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidmlwMiIsImdyYWRlIjoyLCJleHAiOjE2NjcwMTI3MDN9.HPfE71HBW-TVazslSxvJ87bNwp3Ra_zluJGoABQ3nPk"
                }
            }
        },
        "define.Res_success": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 1
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.ApartmentBasic": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer",
                    "example": 8848
                },
                "apt_address": {
                    "type": "string",
                    "example": "超商B区二期三楼北面电梯旁"
                },
                "apt_id": {
                    "type": "string",
                    "example": "dz1-relx06"
                },
                "apt_name": {
                    "type": "string",
                    "example": "悦刻销售部"
                },
                "apt_tel": {
                    "type": "string",
                    "example": "18355555555"
                },
                "father_id": {
                    "type": "integer",
                    "example": 666
                }
            }
        },
        "models.MallBasic": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer",
                    "example": 666
                },
                "mall_address": {
                    "type": "string",
                    "example": "四川省甘孜藏族自治州理塘县朱雀大道1-1"
                },
                "mall_id": {
                    "type": "string",
                    "example": "dingzhen001"
                },
                "mall_name": {
                    "type": "string",
                    "example": "丁真烟酒专卖超商"
                },
                "mall_tel": {
                    "type": "string",
                    "example": "400-114514"
                }
            }
        },
        "models.StaffBasic": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer",
                    "example": 114514
                },
                "father_id": {
                    "type": "integer",
                    "example": 8848
                },
                "staff_address": {
                    "type": "string",
                    "example": "销售经理"
                },
                "staff_id": {
                    "type": "string",
                    "example": "dz1r6-zhenzhu"
                },
                "staff_name": {
                    "type": "string",
                    "example": "珍珠"
                },
                "staff_sal": {
                    "type": "number",
                    "example": 100000
                },
                "staff_tel": {
                    "type": "string",
                    "example": "18355555555"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
