name: Build docker image and push to aliyun registry

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: baizhukui-image-repo
  IMAGE: mall-admin-be

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          "${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}"
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
          type=raw,value=latest

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action
    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: "./Dockerfile"


