name: release

on:
  push:
    branches: [ "main" ] # master 分支提交时触发
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go #配置GO 环境
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build # 编译项目
      run: go build -v ./

    - name: 拉取编译结果到腾讯云
      uses: easingthemes/ssh-deploy@main
      env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          #SCp参数
          ARGS: "-rltgoDzvO --delete"
          #源目录
          SOURCE: "./"
          #服务器Ip:换成你的服务器iP
          REMOTE_HOST:  ${{ secrets.HOST }}
          #用户
          REMOTE_USER: "ubuntu"
          #目标地址
          TARGET: "/home/ubuntu/work/bin"
          
    - name: Run
      uses: appleboy/ssh-action@master
      with:
        host:  ${{ HOST }}
        username: "ubuntu"
        password: ${{ PWD }}
        script: |
          cd /home/ubuntu/work/bin
          ./mall
          exit
